// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Place struct {
	Rate        *int       `json:"rate,omitempty"`
	Name        *string    `json:"name,omitempty"`
	Kinds       *string    `json:"kinds,omitempty"`
	Type        *string    `json:"type,omitempty"`
	Coordinates []*float64 `json:"coordinates,omitempty"`
}

type Query struct {
}
